### ISSUE TITLE
Suggestion: Should I add docs for Spicetify Creator?

### ISSUE THREAD

**Issue by FlafyDev** [afonsojramos/spicetify-docs#22]
I've been working on a project to simplify and modernize the coding process for extensions and custom apps.
Unlike current methods for creating extensions and custom apps, [Spicetify Creator](https://github.com/FlafyDev/spicetify-creator) allows importing packages, using react typescript syntax, and more.

I think this improves the coding process tremendously and I want to show it to more people.
So if you think this is a good idea I can start creating docs.

**Comment by afonsojramos** [comment]
For sure! I've seen your work on Discord 👀

Please do open a PR 🚀
